export type RoutePermission =
  | "public"
  | "authenticated"
  | "self"
  | "owner"
  | "read-member"
  | "responder"
  | "distinct-reviewer"
  | "admin-or-distinct-reviewer";

/** This inventory mirrors every procedure exported by server/routers.ts. */
export const routedProcedurePermissions = {
  "auth.me": "public",
  "auth.logout": "public",
  "agent.analyzeEvidence": "responder",
  "agent.analyzeAndCreateFinding": "responder",
  "agent.importPassiveInventory": "responder",
  "agent.composeReport": "responder",
  "agent.validateReport": "read-member",
  "agent.extractArtifact": "read-member",
  "agent.analytics": "read-member",
  "agent.importWorkspaceInventory": "owner",
  "agent.listWorkspaceInventory": "read-member",
  "agent.saveReportVersion": "owner",
  "agent.listReportVersions": "read-member",
  "control.dashboard": "authenticated",
  "notification.list": "self",
  "notification.listSince": "self",
  "notification.deliveryLedger": "self",
  "notification.preferences": "self",
  "notification.setPreference": "self",
  "notification.markRead": "self",
  "notification.markAllRead": "self",
  "tools.catalog": "read-member",
  "tools.search": "read-member",
  "tools.summary": "read-member",
  "tools.runtimeAdapters": "read-member",
  "tools.runtimeHealth": "read-member",
  "tools.run": "responder",
  "operations.members": "owner",
  "operations.addMember": "owner",
  "operations.removeMember": "owner",
  "operations.webhook": "owner",
  "operations.saveWebhookDraft": "owner",
  "operations.archives": "owner",
  "operations.createArchive": "owner",
  "operations.verifyArchive": "owner",
  "operations.restoreArchivePlan": "owner",
  "operations.runRestoreDrill": "owner",
  "assurance.policies": "read-member",
  "assurance.requestPolicy": "owner",
  "assurance.decidePolicy": "admin-or-distinct-reviewer",
  "assurance.comparePolicies": "read-member",
  "assurance.incidents": "read-member",
  "assurance.createIncident": "responder",
  "assurance.acknowledgeIncident": "responder",
  "assurance.resolveIncident": "responder",
  "assurance.incidentReview": "read-member",
  "assurance.saveIncidentReview": "responder",
  "assurance.incidentEvidence": "read-member",
  "assurance.linkIncidentEvidence": "responder",
  "assurance.webhookActivationRequests": "read-member",
  "assurance.requestWebhookActivation": "owner",
  "assurance.decideWebhookActivation": "admin-or-distinct-reviewer",
  "workspace.list": "authenticated",
  "workspace.create": "authenticated",
  "workspace.setStatus": "owner",
  "workspace.credentials": "owner",
  "workspace.addCredentialReference": "owner",
  "workspace.scheduleAdministrativeCheck": "owner",
  "ai.models": "read-member",
  "ai.registerModel": "admin-or-distinct-reviewer",
  "ai.recordModelHealth": "admin-or-distinct-reviewer",
  "ai.runs": "read-member",
  "ai.evaluations": "read-member",
  "ai.evaluateRun": "distinct-reviewer",
  "ai.startRun": "responder",
  "ai.updateRun": "responder",
  "ai.enqueueJob": "responder",
  "ai.jobs": "read-member",
  "ai.publishEvent": "responder",
  "rehearsal.run": "owner",
  "rehearsal.listRuns": "read-member",
  "finding.comments": "read-member",
  "finding.addComment": "read-member",
  "search.global": "read-member",
  "knowledge.graph": "read-member",
  "knowledge.upsertNode": "responder",
  "knowledge.createEdge": "responder",
  "knowledge.traverse": "read-member",
  "research.ingestIntelligenceFeed": "responder",
  "research.enqueueIntelligenceFetch": "responder",
  "research.promoteObservationToFinding": "responder",
  "research.playbookRuns": "read-member",
  "research.transitionPlaybookRun": "responder",
  "organization.previewProgramScope": "read-member",
  "organization.submissions": "read-member",
  "organization.submissionEvents": "read-member",
  "organization.createSubmission": "responder",
  "organization.transitionSubmission": "responder",
  "governance.list": "admin-or-distinct-reviewer",
  "governance.requestTier3": "owner",
  "governance.decide": "admin-or-distinct-reviewer",
  "finding.list": "read-member",
  "finding.create": "owner",
  "finding.transition": "owner",
  "finding.approveReview": "owner",
  "evidence.list": "read-member",
  "evidence.recordProvenance": "responder",
  "evidence.linkResearchNode": "responder",
  "evidence.findingRelations": "read-member",
  "evidence.duplicateCandidates": "read-member",
  "evidence.linkFindingRelation": "responder",
  "evidence.findingRetests": "read-member",
  "evidence.requestRetest": "responder",
  "evidence.completeRetest": "responder",
  "evidence.qualityGate": "responder",
  "audit.list": "read-member",
  "audit.evidence": "read-member",
  "audit.uploadEvidence": "owner",
} as const satisfies Record<string, RoutePermission>;

export function permissionNeedsWorkspaceRole(
  permission: RoutePermission
): boolean {
  return [
    "owner",
    "read-member",
    "responder",
    "distinct-reviewer",
    "admin-or-distinct-reviewer",
  ].includes(permission);
}
