import type { Express, Request, Response } from "express";
import { z } from "zod";
import { sdk } from "./_core/sdk";
import { canAccessWorkspace } from "./control-plane/operations";
import { createAiWorker, getAiAutomationQuality, getAiWorker, getAutomationCatalog, listAiWorkers, listPrompts, registerPrompt, routeAutomation, runAiWorker, setAiWorkerEnabled } from "./ai-automation";
const workerSchema = z.object({ workspaceId: z.number().int().positive(), name: z.string().min(2), role: z.enum(["research", "analysis", "triage", "report"]), modelKey: z.string().min(2), budgetCents: z.number().int().min(0), timeoutSeconds: z.number().int().min(1).max(3600), mode: z.enum(["simulation", "governed"]).optional() });
const promptSchema = z.object({ name: z.string().min(2), template: z.string().min(2) });
const routeSchema = z.object({ capabilities: z.array(z.string()).optional(), minimumContextWindow: z.number().int().nonnegative().optional(), maxCostCentsPerMillionTokens: z.number().nonnegative().optional() });
const runSchema = z.object({ purpose: z.string().min(2), inputReference: z.string().min(2), estimatedCostCents: z.number().int().min(0).optional() });
async function userId(req: Request) { const user = await sdk.authenticateRequest(req); return user.id; }
export function registerAiAutomationRestV1Routes(app: Express) {
  app.get("/api/v1/ai/automation/catalog", async (_req, res) => { try { res.json({ ok: true, data: await getAutomationCatalog() }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : "AI catalog failed" }); } });
  app.post("/api/v1/ai/workers", async (req, res) => { try { const uid = await userId(req); const input = workerSchema.parse(req.body); if (!(await canAccessWorkspace(uid, input.workspaceId, "respond"))) return res.status(403).json({ ok: false, error: "Forbidden" }); res.status(201).json({ ok: true, data: createAiWorker(input) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Invalid worker" }); } });
  app.get("/api/v1/workspaces/:workspaceId/ai/workers", async (req, res) => { try { const uid = await userId(req); const workspaceId = Number(req.params.workspaceId); if (!(await canAccessWorkspace(uid, workspaceId, "read"))) return res.status(403).json({ ok: false, error: "Forbidden" }); res.json({ ok: true, data: listAiWorkers(workspaceId) }); } catch (error) { res.status(401).json({ ok: false, error: error instanceof Error ? error.message : "Unauthorized" }); } });
  app.post("/api/v1/ai/workers/:id/enabled", async (req, res) => { try { const uid = await userId(req); const worker = getAiWorker(req.params.id); if (!(await canAccessWorkspace(uid, worker.workspaceId, "respond"))) return res.status(403).json({ ok: false, error: "Forbidden" }); res.json({ ok: true, data: setAiWorkerEnabled(worker.id, Boolean(req.body?.enabled)) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Worker update failed" }); } });
  app.post("/api/v1/ai/workers/:id/run", async (req, res) => { try { const uid = await userId(req); const worker = getAiWorker(req.params.id); if (!(await canAccessWorkspace(uid, worker.workspaceId, "respond"))) return res.status(403).json({ ok: false, error: "Forbidden" }); const input = runSchema.parse(req.body); res.json({ ok: true, data: await runAiWorker({ userId: uid, workerId: worker.id, ...input }) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Worker run failed" }); } });
  app.post("/api/v1/ai/prompts", async (req, res) => { try { await userId(req); res.status(201).json({ ok: true, data: registerPrompt(promptSchema.parse(req.body)) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Invalid prompt" }); } });
  app.get("/api/v1/ai/prompts", async (req, res) => { try { await userId(req); res.json({ ok: true, data: listPrompts(typeof req.query.name === "string" ? req.query.name : undefined) }); } catch (error) { res.status(401).json({ ok: false, error: error instanceof Error ? error.message : "Unauthorized" }); } });
  app.post("/api/v1/ai/route", async (req, res) => { try { await userId(req); res.json({ ok: true, data: await routeAutomation(routeSchema.parse(req.body)) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Routing failed" }); } });
  app.get("/api/v1/workspaces/:workspaceId/ai/quality", async (req, res) => { try { const uid = await userId(req); const workspaceId = Number(req.params.workspaceId); if (!(await canAccessWorkspace(uid, workspaceId, "read"))) return res.status(403).json({ ok: false, error: "Forbidden" }); res.json({ ok: true, data: await getAiAutomationQuality(uid, workspaceId) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : "Quality query failed" }); } });
}
