import { Eyebrow, NeonFrame } from "@/components/NeonFrame";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Activity, BrainCircuit, Clock3, DollarSign, ListTodo, Play, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function AICenter() {
  const workspaces = trpc.workspace.list.useQuery();
  const [workspaceId, setWorkspaceId] = useState<number>();
  const selectedWorkspaceId = workspaceId ?? workspaces.data?.[0]?.id;
  const models = trpc.ai.models.useQuery();
  const runs = trpc.ai.runs.useQuery({ workspaceId: selectedWorkspaceId! }, { enabled: Boolean(selectedWorkspaceId) });
  const jobs = trpc.ai.jobs.useQuery({ workspaceId: selectedWorkspaceId }, { enabled: Boolean(selectedWorkspaceId) });
  const [modelKey, setModelKey] = useState("");
  const [purpose, setPurpose] = useState("research-analysis");
  const [inputReference, setInputReference] = useState("research-context");
  const [jobKind, setJobKind] = useState("research-processing");
  const utils = trpc.useUtils();
  useEffect(() => { if (!modelKey && models.data?.[0]?.modelKey) setModelKey(models.data[0].modelKey); }, [modelKey, models.data]);
  const refresh = () => { void models.refetch(); void runs.refetch(); void jobs.refetch(); };
  const startRun = trpc.ai.startRun.useMutation({ onSuccess: () => { void runs.refetch(); toast.success("AI run trace dibuat dengan status queued."); }, onError: error => toast.error(error.message) });
  const enqueueJob = trpc.ai.enqueueJob.useMutation({ onSuccess: () => { void jobs.refetch(); toast.success("Job dimasukkan ke durable queue."); }, onError: error => toast.error(error.message) });
  const selectedModel = models.data?.find(model => model.modelKey === modelKey);

  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Eyebrow>AI center / governed orchestration</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">AI <span className="neon-pink">Center</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Model registry, AI run trace, cost guard, durable jobs, dan outbox siap dipantau dari satu surface. Tidak ada target execution atau credential access dari AI layer.</p></div><Button variant="outline" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4" />Refresh center</Button></header>
    <NeonFrame className="p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[.8fr_1fr_1fr_auto] lg:items-end"><div className="space-y-2"><Label htmlFor="ai-workspace">Workspace</Label><select id="ai-workspace" value={selectedWorkspaceId ?? ""} onChange={event => setWorkspaceId(Number(event.target.value))} className="h-10 w-full border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Create a workspace first</option>{workspaces.data?.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="ai-model">Model</Label><select id="ai-model" value={modelKey} onChange={event => setModelKey(event.target.value)} className="h-10 w-full border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Register a model first</option>{models.data?.map(model => <option key={model.modelKey} value={model.modelKey}>{model.modelKey} · {model.provider}</option>)}</select></div><div className="space-y-2"><Label htmlFor="ai-purpose">Purpose</Label><Input id="ai-purpose" value={purpose} onChange={event => setPurpose(event.target.value)} maxLength={120} /></div><Button disabled={!selectedWorkspaceId || !modelKey || startRun.isPending} onClick={() => selectedWorkspaceId && startRun.mutate({ workspaceId: selectedWorkspaceId, modelKey, gateway: selectedModel?.gateway ?? "configured-gateway", purpose, inputReference })}><Play className="mr-2 h-4 w-4" />Start traced run</Button></div><p className="mt-4 text-xs text-slate-500">Input reference <span className="text-cyan-200">{inputReference}</span>. Cost ceiling is enforced from workspace budget before a run is queued.</p></NeonFrame>
    <div className="grid gap-6 lg:grid-cols-3"><NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><Eyebrow>Model registry</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{models.data?.length ?? 0} active</h2></div><BrainCircuit className="h-5 w-5 text-cyan-300" /></div><div className="mt-5 space-y-2">{models.data?.map(model => <div key={model.id} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-white">{model.modelKey}</p><Badge variant="outline" className="border-emerald-300/40 text-emerald-200">{model.status}</Badge></div><p className="mt-1 text-xs text-slate-500">{model.provider} via {model.gateway} · context {model.contextWindow.toLocaleString()}</p></div>)}</div></NeonFrame><NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><Eyebrow>AI run trace</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{runs.data?.length ?? 0} runs</h2></div><Activity className="h-5 w-5 text-fuchsia-300" /></div><div className="mt-5 space-y-2">{runs.data?.slice(0, 8).map(run => <div key={run.id} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold text-white">{run.purpose}</p><Badge variant="outline" className="border-cyan-300/40 text-cyan-200">{run.status}</Badge></div><p className="mt-1 truncate text-xs text-slate-500">{run.modelKey} · trace {run.traceId.slice(0, 12)}… · {run.costCents} cents</p></div>)}</div></NeonFrame><NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><Eyebrow>Durable jobs</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{jobs.data?.length ?? 0} jobs</h2></div><ListTodo className="h-5 w-5 text-cyan-300" /></div><div className="mt-5 flex gap-2"><Input value={jobKind} onChange={event => setJobKind(event.target.value)} placeholder="Job kind" maxLength={80} /><Button disabled={!selectedWorkspaceId || jobKind.trim().length < 2 || enqueueJob.isPending} onClick={() => selectedWorkspaceId && enqueueJob.mutate({ workspaceId: selectedWorkspaceId, kind: jobKind, idempotencyKey: `${jobKind}-${Date.now()}`, payload: { source: "ai-center" } })}><ListTodo className="h-4 w-4" /></Button></div><div className="mt-4 space-y-2">{jobs.data?.slice(0, 6).map(job => <div key={job.id} className="flex items-center justify-between gap-3 rounded-lg border border-white/10 p-3"><div><p className="text-sm font-semibold text-white">{job.kind}</p><p className="mt-1 text-xs text-slate-500">attempt {job.attempts}/{job.maxAttempts}</p></div><Badge variant="outline" className="border-fuchsia-300/40 text-fuchsia-200">{job.status}</Badge></div>)}</div></NeonFrame></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/[.03] p-4"><DollarSign className="h-4 w-4 text-cyan-300" /><p className="mt-3 text-xs uppercase tracking-[.14em] text-slate-500">Cost governance</p><p className="mt-2 text-sm text-slate-300">Workspace budget guard aktif sebelum run masuk queue.</p></div><div className="rounded-xl border border-fuchsia-300/15 bg-fuchsia-300/[.03] p-4"><Clock3 className="h-4 w-4 text-fuchsia-300" /><p className="mt-3 text-xs uppercase tracking-[.14em] text-slate-500">Failure isolation</p><p className="mt-2 text-sm text-slate-300">Status partial, failed, retrying, dan dead-letter dipisahkan dari workflow utama.</p></div><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.03] p-4"><Activity className="h-4 w-4 text-emerald-300" /><p className="mt-3 text-xs uppercase tracking-[.14em] text-slate-500">Provenance</p><p className="mt-2 text-sm text-slate-300">Trace ID, input reference, output reference, model, gateway, dan cost tersimpan.</p></div></div>
  </div>;
}
