import { Eyebrow, NeonFrame } from "@/components/NeonFrame";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { MessageSquare, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Collaboration() {
  const workspaces = trpc.workspace.list.useQuery();
  const [workspaceId, setWorkspaceId] = useState<number>();
  const selectedWorkspaceId = workspaceId ?? workspaces.data?.[0]?.id;
  const findings = trpc.finding.list.useQuery({ workspaceId: selectedWorkspaceId }, { enabled: Boolean(selectedWorkspaceId) });
  const [findingId, setFindingId] = useState<number>();
  const selectedFindingId = findingId ?? findings.data?.[0]?.id;
  const comments = trpc.finding.comments.useQuery({ workspaceId: selectedWorkspaceId!, findingId: selectedFindingId! }, { enabled: Boolean(selectedWorkspaceId && selectedFindingId) });
  const [body, setBody] = useState("");
  const utils = trpc.useUtils();
  const addComment = trpc.finding.addComment.useMutation({ onSuccess: () => { setBody(""); void utils.finding.comments.invalidate(); toast.success("Comment added to the review thread."); }, onError: error => toast.error(error.message) });
  const approve = trpc.finding.approveReview.useMutation({ onSuccess: () => { void utils.finding.list.invalidate(); toast.success("Finding review approved."); }, onError: error => toast.error(error.message) });
  const selected = findings.data?.find(item => item.id === selectedFindingId);
  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Eyebrow>Collaboration layer / human review</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">Review <span className="neon-pink">Room</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Satu tempat untuk memilih finding, membaca thread review, menyebut rekan dengan @mention, dan menyelesaikan approval berbasis permission.</p></div><Button variant="outline" onClick={() => { void findings.refetch(); void comments.refetch(); }} disabled={findings.isFetching || comments.isFetching}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></header>
    <NeonFrame className="p-5 sm:p-6"><div className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><div className="space-y-3"><label className="font-mono text-[10px] uppercase tracking-[.2em] text-cyan-300" htmlFor="collab-workspace">Workspace</label><select id="collab-workspace" value={selectedWorkspaceId ?? ""} onChange={event => { setWorkspaceId(Number(event.target.value)); setFindingId(undefined); }} className="h-10 w-full border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Select workspace</option>{workspaces.data?.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select><label className="pt-2 font-mono text-[10px] uppercase tracking-[.2em] text-cyan-300" htmlFor="collab-finding">Finding</label><select id="collab-finding" value={selectedFindingId ?? ""} onChange={event => setFindingId(Number(event.target.value))} className="h-10 w-full border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Select finding</option>{findings.data?.map(item => <option key={item.id} value={item.id}>#{item.id} · {item.title}</option>)}</select></div><div className="min-w-0 rounded-lg border border-white/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-fuchsia-300">Selected finding</p><h2 className="mt-2 text-xl font-bold text-white">{selected?.title ?? "Choose a finding"}</h2></div>{selected && <div className="flex gap-2"><Badge variant="outline" className="border-fuchsia-300/40 text-fuchsia-200">{selected.severity}</Badge><Badge variant="outline" className="border-cyan-300/40 text-cyan-200">{selected.status}</Badge></div>}</div>{selected && <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => approve.mutate({ findingId: selected.id })} disabled={approve.isPending}><ShieldCheck className="mr-2 h-4 w-4" />Approve review</Button><span className="self-center text-xs text-slate-500">Revision {selected.revision} · confidence {selected.confidence}%</span></div>}</div></div></NeonFrame>
    <NeonFrame className="p-5 sm:p-6"><div className="flex items-center gap-3"><MessageSquare className="h-5 w-5 text-cyan-300" /><div><Eyebrow>Threaded collaboration</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">Review discussion</h2></div></div><div className="mt-5 space-y-3">{comments.data?.length ? comments.data.map(comment => <div key={comment.id} className="rounded-lg border border-white/10 p-4"><div className="flex justify-between gap-3"><span className="font-mono text-[10px] text-cyan-300">USER #{comment.authorUserId}</span><span className="text-[10px] text-slate-500">{new Date(comment.createdAt).toLocaleString()}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{comment.body}</p>{comment.parentCommentId && <p className="mt-2 text-[10px] text-fuchsia-300">Reply to comment #{comment.parentCommentId}</p>}</div>) : <p className="py-8 text-center text-sm text-slate-500">Belum ada komentar. Mulai thread review dengan catatan yang dapat ditindaklanjuti.</p>}</div><form className="mt-5 flex gap-3 border-t border-white/10 pt-5" onSubmit={event => { event.preventDefault(); if (selectedWorkspaceId && selectedFindingId && body.trim()) addComment.mutate({ workspaceId: selectedWorkspaceId, findingId: selectedFindingId, body }); }}><Textarea aria-label="Review comment" value={body} onChange={event => setBody(event.target.value)} placeholder="Tulis review… gunakan @username untuk mention anggota workspace" maxLength={4000} className="min-h-20" /><Button type="submit" disabled={!selectedFindingId || body.trim().length < 1 || addComment.isPending}><Send className="mr-2 h-4 w-4" />Post</Button></form></NeonFrame>
  </div>;
}
