import { Eyebrow, NeonFrame } from "@/components/NeonFrame";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Building2, FileCheck2, Plus, Users2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const lines = (value: string) => value.split(/\r?\n|,/).map(item => item.trim()).filter(Boolean);

export default function Organizations() {
  const organizations = trpc.organization.list.useQuery();
  const [organizationId, setOrganizationId] = useState<number>();
  const selectedOrganizationId = organizationId ?? organizations.data?.[0]?.id;
  const members = trpc.organization.members.useQuery({ organizationId: selectedOrganizationId! }, { enabled: Boolean(selectedOrganizationId) });
  const programs = trpc.organization.programs.useQuery({ organizationId: selectedOrganizationId! }, { enabled: Boolean(selectedOrganizationId) });
  const utils = trpc.useUtils();
  const [organizationName, setOrganizationName] = useState("");
  const [memberEmail, setMemberEmail] = useState("");
  const [memberRole, setMemberRole] = useState<"admin" | "researcher" | "reviewer" | "auditor">("researcher");
  const [programName, setProgramName] = useState("");
  const [programDescription, setProgramDescription] = useState("");
  const [includedAssets, setIncludedAssets] = useState("");
  const [excludedAssets, setExcludedAssets] = useState("");
  const [rules, setRules] = useState("");
  const [safeHarbor, setSafeHarbor] = useState("");
  useEffect(() => { if (!organizationId && organizations.data?.[0]?.id) setOrganizationId(organizations.data[0].id); }, [organizationId, organizations.data]);
  const refresh = () => { void organizations.refetch(); void members.refetch(); void programs.refetch(); };
  const createOrganization = trpc.organization.create.useMutation({ onSuccess: result => { setOrganizationId(result.id); setOrganizationName(""); refresh(); toast.success("Organization dibuat."); }, onError: error => toast.error(error.message) });
  const addMember = trpc.organization.addMember.useMutation({ onSuccess: () => { setMemberEmail(""); void members.refetch(); toast.success("Member role diperbarui."); }, onError: error => toast.error(error.message) });
  const createProgram = trpc.organization.createProgram.useMutation({ onSuccess: () => { setProgramName(""); setProgramDescription(""); setIncludedAssets(""); setExcludedAssets(""); setRules(""); setSafeHarbor(""); void programs.refetch(); toast.success("Program dibuat dalam status draft."); }, onError: error => toast.error(error.message) });
  const setProgramStatus = trpc.organization.setProgramStatus.useMutation({ onSuccess: () => { void programs.refetch(); toast.success("Program status diperbarui."); }, onError: error => toast.error(error.message) });
  const selectedOrganization = organizations.data?.find(item => item.id === selectedOrganizationId);

  return <div className="mx-auto max-w-7xl space-y-6"><header><Eyebrow>Organization / tenant isolation</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">Organization <span className="neon-pink">Hub</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Kelola tenant, role member, dan program scope dalam boundary yang sama. Workspace baru dapat dihubungkan ke program yang sudah disetujui melalui API server-side.</p></header>
    <NeonFrame className="p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_1fr_auto] lg:items-end"><div className="space-y-2"><Label htmlFor="organization-select">Active organization</Label><select id="organization-select" value={selectedOrganizationId ?? ""} onChange={event => setOrganizationId(Number(event.target.value))} className="h-10 w-full border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Create an organization first</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name} · {org.role}</option>)}</select></div><div className="space-y-2"><Label htmlFor="organization-name">New organization</Label><Input id="organization-name" value={organizationName} onChange={event => setOrganizationName(event.target.value)} placeholder="AngelMind Research" maxLength={160} /></div><Button disabled={organizationName.trim().length < 2 || createOrganization.isPending} onClick={() => createOrganization.mutate({ name: organizationName })}><Plus className="mr-2 h-4 w-4" />Create organization</Button></div></NeonFrame>
    {selectedOrganization && <><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><Eyebrow>Members & roles</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{members.data?.length ?? 0} members</h2></div><Users2 className="h-5 w-5 text-cyan-300" /></div><div className="mt-5 space-y-3"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input value={memberEmail} onChange={event => setMemberEmail(event.target.value)} placeholder="member@example.com" type="email" maxLength={320} /><select aria-label="Member role" value={memberRole} onChange={event => setMemberRole(event.target.value as typeof memberRole)} className="h-10 border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="researcher">researcher</option><option value="reviewer">reviewer</option><option value="auditor">auditor</option><option value="admin">admin</option></select></div><Button variant="outline" disabled={!selectedOrganizationId || !memberEmail.includes("@") || addMember.isPending} onClick={() => selectedOrganizationId && addMember.mutate({ organizationId: selectedOrganizationId, email: memberEmail, role: memberRole })}>Add member</Button></div><div className="mt-5 space-y-2">{members.data?.map(member => <div className="flex items-center justify-between rounded-lg border border-white/10 p-3" key={member.id}><span className="text-sm text-white">User #{member.userId}</span><Badge variant="outline" className="border-cyan-300/40 text-cyan-200">{member.role}</Badge></div>)}</div></NeonFrame>
      <NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><Eyebrow>Program catalog / scope</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{programs.data?.length ?? 0} programs</h2></div><FileCheck2 className="h-5 w-5 text-fuchsia-300" /></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Input value={programName} onChange={event => setProgramName(event.target.value)} placeholder="Program name" maxLength={200} /><Input value={programDescription} onChange={event => setProgramDescription(event.target.value)} placeholder="Short description" maxLength={20_000} /><Textarea value={includedAssets} onChange={event => setIncludedAssets(event.target.value)} placeholder="Included assets, one per line" maxLength={100_000} /><Textarea value={excludedAssets} onChange={event => setExcludedAssets(event.target.value)} placeholder="Excluded assets, one per line" maxLength={100_000} /><Textarea value={rules} onChange={event => setRules(event.target.value)} placeholder="Rules and restrictions, one per line" maxLength={100_000} /><Textarea value={safeHarbor} onChange={event => setSafeHarbor(event.target.value)} placeholder="Safe harbor terms" maxLength={20_000} /></div><Button className="mt-4" disabled={!selectedOrganizationId || programName.trim().length < 3 || lines(includedAssets).length === 0 || safeHarbor.trim().length < 10 || createProgram.isPending} onClick={() => selectedOrganizationId && createProgram.mutate({ organizationId: selectedOrganizationId, name: programName, description: programDescription, includedAssets: lines(includedAssets), excludedAssets: lines(excludedAssets), rules: lines(rules), safeHarbor })}><Plus className="mr-2 h-4 w-4" />Create draft program</Button><div className="mt-5 space-y-3">{programs.data?.map(program => <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/10 p-4" key={program.id}><div><p className="font-semibold text-white">{program.name}</p><p className="mt-1 text-xs text-slate-500">{program.includedAssets.length} bytes scope manifest · version {program.currentVersion}</p></div><div className="flex items-center gap-2"><Badge variant="outline" className="border-fuchsia-300/40 text-fuchsia-200">{program.status}</Badge>{program.status === "draft" && <Button size="sm" variant="outline" onClick={() => setProgramStatus.mutate({ programId: program.id, status: "active" })}>Activate</Button>}</div></div>)}</div></NeonFrame></div></>}
  </div>;
}
