import { Eyebrow, NeonFrame } from "@/components/NeonFrame";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ChevronLeft, Loader2, Search as SearchIcon, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

const typeLabels: Record<string, string> = { finding: "Findings", asset: "Assets", session: "Sessions", report: "Reports", program: "Programs", knowledge_node: "Knowledge", observation: "Observations", hypothesis: "Hypotheses", task: "Tasks", evidence: "Evidence", intelligence: "Intelligence", note: "Notes", ai_memory: "AI memory" };
const typeRoutes: Record<string, string> = { finding: "/findings", asset: "/inventory", session: "/research", report: "/reports", knowledge_node: "/knowledge", observation: "/research", hypothesis: "/research", task: "/research", evidence: "/research", intelligence: "/coverage", note: "/tags-notes", ai_memory: "/ai-center", program: "/workspaces" };

export default function Search() {
  const workspaces = trpc.workspace.list.useQuery();
  const [workspaceId, setWorkspaceId] = useState<number>();
  const selectedWorkspaceId = workspaceId ?? workspaces.data?.[0]?.id;
  const [draft, setDraft] = useState("");
  const [query, setQuery] = useState("");
  const [entityType, setEntityType] = useState("");
  const [freshnessDays, setFreshnessDays] = useState<string>("");
  const [cursor, setCursor] = useState<string>();
  const search = trpc.search.global.useQuery({ workspaceId: selectedWorkspaceId!, query, limit: 24, cursor, entityTypes: entityType ? [entityType] : undefined, freshnessDays: freshnessDays ? Number(freshnessDays) : undefined }, { enabled: Boolean(selectedWorkspaceId && query.length >= 2), placeholderData: previous => previous });
  useEffect(() => { const params = new URLSearchParams(window.location.search); const initial = params.get("q") ?? ""; if (initial) { setDraft(initial); setQuery(initial); } }, []);
  const facets = useMemo(() => Object.entries(search.data?.facets ?? {}).sort((a, b) => b[1] - a[1]), [search.data?.facets]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); setCursor(undefined); setQuery(draft.trim()); };
  const reset = () => { setDraft(""); setQuery(""); setCursor(undefined); setEntityType(""); setFreshnessDays(""); };
  return <div className="mx-auto max-w-7xl space-y-6">
    <header><Eyebrow>Unified intelligence layer / semantic retrieval</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">Global <span className="neon-pink">Search</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Cari lintas findings, assets, evidence, reports, knowledge, notes, dan AI memory dalam workspace yang terisolasi. Ranking menggabungkan exact match, token relevance, kemiripan n-gram, dan freshness.</p></header>
    <NeonFrame className="p-5 sm:p-6"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]"><form onSubmit={submit} className="flex gap-2"><div className="relative min-w-0 flex-1"><SearchIcon className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-cyan-300" /><Input aria-label="Search workspace" className="pl-9" value={draft} onChange={event => setDraft(event.target.value)} placeholder="Search evidence, finding, hostname, hypothesis…" maxLength={120} /></div><Button type="submit" disabled={!selectedWorkspaceId || draft.trim().length < 2 || search.isFetching}><SearchIcon className="mr-2 h-4 w-4" />Search</Button></form><select aria-label="Workspace" value={selectedWorkspaceId ?? ""} onChange={event => { setWorkspaceId(Number(event.target.value)); setCursor(undefined); }} className="h-10 border border-cyan-300/20 bg-[#0a0d19] px-3 text-sm text-slate-200"><option value="">Select workspace</option>{workspaces.data?.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></div><div className="mt-4 flex flex-wrap items-center gap-2 text-xs text-slate-400"><SlidersHorizontal className="h-3.5 w-3.5 text-cyan-300" /><select aria-label="Entity type filter" value={entityType} onChange={event => { setEntityType(event.target.value); setCursor(undefined); }} className="h-8 border border-white/10 bg-[#0a0d19] px-2"><option value="">All domains</option>{facets.map(([type]) => <option key={type} value={type}>{typeLabels[type] ?? type}</option>)}</select><select aria-label="Freshness filter" value={freshnessDays} onChange={event => { setFreshnessDays(event.target.value); setCursor(undefined); }} className="h-8 border border-white/10 bg-[#0a0d19] px-2"><option value="">Any age</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="365">Last year</option></select>{query && <Button type="button" variant="ghost" size="sm" onClick={reset}>Clear</Button>}</div></NeonFrame>
    {query.length < 2 ? <NeonFrame className="p-12 text-center"><SearchIcon className="mx-auto h-8 w-8 text-cyan-300/50" /><p className="mt-4 text-sm text-slate-400">Masukkan minimal dua karakter untuk memulai pencarian workspace.</p></NeonFrame> : search.isLoading ? <NeonFrame className="p-12 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-300" /></NeonFrame> : <NeonFrame className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><Eyebrow>Search results</Eyebrow><h2 className="mt-2 font-display text-2xl font-bold text-white">{search.data?.results.length ?? 0} results <span className="text-slate-500">for “{query}”</span></h2></div><div className="flex flex-wrap justify-end gap-2">{facets.map(([type, count]) => <Badge key={type} variant="outline" className="border-cyan-300/30 text-cyan-200">{typeLabels[type] ?? type}: {count}</Badge>)}</div></div><div className="mt-5 space-y-3">{search.data?.results.map(result => <Link key={`${result.entityType}-${result.id}`} href={`${typeRoutes[result.entityType] ?? "/"}?id=${result.id}`} className="block rounded-lg border border-white/10 p-4 transition hover:border-cyan-300/40 hover:bg-cyan-300/[.04]"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold text-white">{result.title || "Untitled"}</h3><Badge variant="outline" className="border-fuchsia-300/30 text-fuchsia-200">{typeLabels[result.entityType] ?? result.entityType}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{result.body || "No additional context"}</p></div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-cyan-300" /></div></Link>)}{!search.data?.results.length && <p className="py-12 text-center text-sm text-slate-500">Tidak ada hasil yang dapat diakses pada workspace ini.</p>}</div>{search.data?.results.length ? <div className="mt-5 flex justify-between border-t border-white/10 pt-4"><Button variant="outline" disabled={!cursor} onClick={() => setCursor(undefined)}><ChevronLeft className="mr-2 h-4 w-4" />First page</Button><Button variant="outline" disabled={!search.data.hasNextPage || !search.data.nextCursor} onClick={() => setCursor(search.data?.nextCursor ?? undefined)}>Next page<ArrowRight className="ml-2 h-4 w-4" /></Button></div> : null}</NeonFrame>}
  </div>;
}
