import { Activity, ShieldCheck, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { NeonFrame, Eyebrow } from "@/components/NeonFrame";
import { trpc } from "@/lib/trpc";

export default function Tools() {
  const catalog = trpc.tools.catalog.useQuery(undefined);
  const summary = trpc.tools.summary.useQuery();
  const health = trpc.tools.runtimeHealth.useQuery();
  return <div className="mx-auto max-w-7xl space-y-6"><header><Eyebrow>Capability registry / runtime health</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">Security <span className="neon-pink">Tools</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Catalog and health are read from the control plane. A catalog entry is not treated as operational until its adapter reports a real health result.</p></header><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Wrench} label="Catalogued" value={String(summary.data?.total ?? catalog.data?.length ?? 0)} /><Metric icon={ShieldCheck} label="Verified" value={String(catalog.data?.filter(tool => tool.verificationStatus === "verified").length ?? 0)} /><Metric icon={Activity} label="Available adapters" value={String(health.data?.filter(item => item.available).length ?? 0)} /></div><NeonFrame className="p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-2">{catalog.data?.map(tool => { const state = health.data?.find(item => item.toolKey === tool.toolKey); return <div className="flex flex-wrap items-center justify-between gap-3 border border-cyan-300/10 p-4" key={tool.toolKey}><div><p className="font-semibold text-white">{tool.name}</p><p className="mt-1 text-xs text-slate-500">{tool.category} · {tool.disposition}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{tool.riskClass}</Badge><Badge className={state?.available ? "border border-cyan-300/30 bg-cyan-300/10 text-cyan-200" : "border border-fuchsia-400/30 bg-fuchsia-400/10 text-fuchsia-200"}>{state?.available ? "Available" : "Not verified"}</Badge></div></div>; }) ?? <p className="py-12 text-center text-sm text-slate-500">Loading tool catalog…</p>}</div></NeonFrame></div>;
}
function Metric({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string }) { return <NeonFrame className="p-4"><Icon className="h-4 w-4 text-cyan-300" /><p className="mt-3 font-mono text-[10px] uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-1 font-display text-3xl font-black text-white">{value}</p></NeonFrame>; }
