import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { NeonFrame, Eyebrow } from "@/components/NeonFrame";
import { WorkspaceSetupDialog } from "@/components/WorkspaceSetupDialog";
import { CredentialReferencesDialog } from "@/components/CredentialReferencesDialog";
import { trpc } from "@/lib/trpc";
import { Archive, CalendarClock, CircleDollarSign, Pause, Play, RadioTower, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { LocalizedDate } from "@/components/LocalizedDate";

export default function Workspaces() {
  const workspaces = trpc.workspace.list.useQuery();
  const utils = trpc.useUtils();
  const setStatus = trpc.workspace.setStatus.useMutation({ onSuccess: () => { utils.workspace.list.invalidate(); utils.control.dashboard.invalidate(); toast.success("Status workspace diperbarui."); }, onError: error => toast.error(error.message) });
  const attachSchedule = trpc.workspace.scheduleAdministrativeCheck.useMutation({ onSuccess: () => { utils.workspace.list.invalidate(); toast.success("Jadwal administratif terpasang untuk deployment aktif."); }, onError: error => toast.error(error.message) });
  const cents = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value / 100);
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Eyebrow>Workspace isolation</Eyebrow><h1 className="mt-2 font-display text-4xl font-black uppercase tracking-[-.05em] text-white">Program <span className="neon-pink">Vaults</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Each program remains owner-scoped with independent scope, safe-harbor, budget, session, cooldown, artifact retention, and scheduling controls.</p></div><WorkspaceSetupDialog /></header><div className="grid gap-5 lg:grid-cols-2">{workspaces.data?.length ? workspaces.data.map(workspace => <NeonFrame className="p-5" key={workspace.id}><div className="flex items-start justify-between gap-4"><div><p className="font-display text-xl font-bold text-white">{workspace.name}</p><p className="mt-1 text-sm text-slate-500">{workspace.programName}</p></div><Badge className={workspace.status === "active" ? "border border-cyan-300/30 bg-cyan-300/10 text-cyan-200" : "border border-slate-600 bg-slate-800 text-slate-300"}>{workspace.status}</Badge></div><div className="mt-5 grid grid-cols-3 gap-3 border-y border-cyan-300/10 py-4"><Datum icon={CircleDollarSign} label="Budget" value={cents(workspace.budgetCents)} /><Datum icon={CalendarClock} label="Cooldown" value={`${workspace.cooldownMinutes}m`} /><Datum icon={ShieldCheck} label="Retention" value={`${workspace.retentionDays}d`} /></div><div className="mt-4"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-cyan-300">Scope allowlist</p><p className="mt-2 line-clamp-2 font-mono text-xs leading-5 text-slate-400">{workspace.allowlist}</p></div><div className="mt-5 flex flex-wrap gap-2">{workspace.status === "active" ? <Button variant="outline" size="sm" onClick={() => setStatus.mutate({ workspaceId: workspace.id, status: "paused" })}><Pause className="mr-2 h-3.5 w-3.5" />Pause</Button> : <Button variant="outline" size="sm" onClick={() => setStatus.mutate({ workspaceId: workspace.id, status: "active" })}><Play className="mr-2 h-3.5 w-3.5" />Activate</Button>}<Button variant="outline" size="sm" onClick={() => setStatus.mutate({ workspaceId: workspace.id, status: "archived" })}><Archive className="mr-2 h-3.5 w-3.5" />Archive</Button><CredentialReferencesDialog workspaceId={workspace.id} workspaceName={workspace.name} />{workspace.status === "active" && !workspace.scheduleCronTaskUid && <Button variant="outline" size="sm" onClick={() => attachSchedule.mutate({ workspaceId: workspace.id, cron: "0 0 2 * * *" })}><RadioTower className="mr-2 h-3.5 w-3.5" />Schedule daily check</Button>}</div>{!workspace.scheduleCronTaskUid && <p className="mt-3 text-[11px] leading-5 text-slate-500">Schedule attaches a daily 02:00 UTC metadata-only check after the app is deployed. It honors active status, cooldown, session limits, and budget; it does not contact targets.</p>}</NeonFrame>) : <EmptyState />}</div></div>;
}
function Datum({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string }) { return <div><Icon className="h-3.5 w-3.5 text-fuchsia-300" /><p className="mt-2 font-mono text-[9px] uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-100">{value}</p></div>; }
function EmptyState() { return <NeonFrame className="col-span-full flex min-h-72 flex-col items-center justify-center p-8 text-center"><ShieldCheck className="h-10 w-10 text-cyan-300" /><p className="mt-5 font-display text-2xl font-bold text-white">No workspace records</p><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Create the first guarded workspace. Nothing can be rehearsed until its safe harbor, conduct, allowlist, exclusions, limits, and retention are recorded.</p></NeonFrame>; }
