import { LanguageSelector } from "@/components/LanguageSelector";
import { Badge } from "@/components/ui/badge";
import { ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import { Link } from "wouter";

const examples = [
  { label: "api.example.rehearsal", method: "POST", endpoint: "/v1/rehearsals/plan", request: '{\n  "workspaceRef": "workspace_demo",\n  "mode": "offline_only"\n}', response: '{\n  "allowed": true,\n  "networkCalls": 0,\n  "status": "planned"\n}' },
  { label: "api.example.policy", method: "POST", endpoint: "/v1/policy/evaluate", request: '{\n  "tier": "tier_3",\n  "proposedAction": "governed_transition"\n}', response: '{\n  "allowed": false,\n  "reason": "human_approval_required"\n}' },
  { label: "api.example.audit", method: "GET", endpoint: "/v1/audit/archive-status", request: "No request body", response: '{\n  "archive": "reference_only",\n  "verified": true,\n  "delivery": "in_app_only"\n}' },
] as const;

export default function ApiPlayground() {
  const { copy } = useLocale(); const [index, setIndex] = useState(0); const current = examples[index];
  return <div className="min-h-screen bg-[#05060b] px-5 py-6 text-slate-100 sm:px-8"><header className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/product" className="font-display text-sm font-black tracking-[.22em] text-fuchsia-300">ANGELMIND</Link><LanguageSelector /></header><main className="mx-auto max-w-6xl pb-20 pt-16"><Badge variant="outline" className="border-cyan-300/40 bg-cyan-300/5 font-mono text-[10px] uppercase tracking-[.16em] text-cyan-200">{copy("api.eyebrow")}</Badge><h1 className="mt-5 max-w-3xl font-display text-5xl font-black uppercase leading-[.94] tracking-[-.045em] text-white sm:text-6xl">{copy("api.title")}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400">{copy("api.description")}</p><div className="mt-10 grid gap-5 lg:grid-cols-[.34fr_.66fr]"><aside className="border border-cyan-300/15 bg-white/[.025] p-3">{examples.map((example, itemIndex) => <button type="button" key={example.endpoint} onClick={() => setIndex(itemIndex)} className={`mb-2 w-full border p-4 text-left transition ${index === itemIndex ? "border-cyan-300/60 bg-cyan-300/10" : "border-transparent hover:border-cyan-300/20"}`}><span className="font-mono text-[10px] text-fuchsia-200">{example.method}</span><span className="mt-2 block text-sm text-slate-100">{copy(example.label)}</span><span className="mt-1 block font-mono text-[10px] text-slate-500">{example.endpoint}</span></button>)}</aside><section className="border border-cyan-300/15 bg-[#0b1020]/80 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">{copy("api.endpoint")}</p><p dir="ltr" className="mt-2 font-mono text-sm text-slate-100"><span className="mr-2 text-fuchsia-300">{current.method}</span>{current.endpoint}</p></div><Badge variant="outline" className="border-amber-300/40 text-amber-100">{copy("api.badge")}</Badge></div><div className="mt-7 grid gap-5 md:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">{copy("api.request")}</p><pre dir="ltr" data-no-localize className="mt-3 min-h-40 overflow-auto border border-cyan-300/10 bg-black/25 p-4 text-xs leading-6 text-cyan-100">{current.request}</pre></div><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">{copy("api.response")}</p><pre dir="ltr" data-no-localize className="mt-3 min-h-40 overflow-auto border border-cyan-300/10 bg-black/25 p-4 text-xs leading-6 text-emerald-100">{current.response}</pre></div></div><div className="mt-6 flex gap-3 border-l-2 border-amber-300/70 bg-amber-300/[.035] p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><p className="font-medium text-amber-50">{copy("api.notice.title")}</p><p className="mt-1 text-sm leading-6 text-amber-100/70">{copy("api.notice.body")}</p></div></div></section></div></main></div>;
}
