import { z } from "zod";
import { protectedProcedure, router } from "./trpc";

const featureInput = z.object({ workspaceId: z.number().int().positive().optional() });
const feature = (name: string, operation: string) =>
  protectedProcedure.input(featureInput).query(({ input }) => ({
    ok: true,
    feature: name,
    operation,
    workspaceId: input.workspaceId ?? null,
  }));

export const apiSurfaceRouter = router({
  authSessions: feature("auth", "sessions.read"),
  authDevices: feature("identity", "devices.read"),
  authCredentials: feature("identity", "credentials.read"),
  organizations: feature("organization", "list"),
  organizationMembers: feature("organization", "members.read"),
  workspaces: feature("workspace", "list"),
  workspaceMembers: feature("workspace", "members.read"),
  workspaceTags: feature("workspace", "tags.read"),
  workspaceNotes: feature("workspace", "notes.read"),
  researches: feature("research", "list"),
  researchTasks: feature("research", "tasks.read"),
  researchHypotheses: feature("research", "hypotheses.read"),
  researchObservations: feature("research", "observations.read"),
  researchEvidence: feature("research", "evidence.read"),
  researchFindings: feature("research", "findings.read"),
  researchExecutions: feature("research", "executions.read"),
  researchTimeline: feature("research", "timeline.read"),
  researchAssets: feature("research", "assets.read"),
  assets: feature("assets", "list"),
  assetRelations: feature("assets", "relations.read"),
  assetFindings: feature("assets", "findings.read"),
  assetEvidence: feature("assets", "evidence.read"),
  tools: feature("tools", "list"),
  toolCapabilities: feature("tools", "capabilities.read"),
  toolHealth: feature("tools", "health.read"),
  toolExecutions: feature("tools", "executions.read"),
  toolOutput: feature("tools", "output.read"),
  aiProviders: feature("ai", "providers.read"),
  aiModels: feature("ai", "models.read"),
  aiConnections: feature("ai", "connections.read"),
  aiRouting: feature("ai", "routing.read"),
  aiUsage: feature("ai", "usage.read"),
  evidence: feature("evidence", "list"),
  evidenceOrigin: feature("evidence", "origin.read"),
  findings: feature("findings", "list"),
  findingComments: feature("findings", "comments.read"),
  findingEvidence: feature("findings", "evidence.read"),
  reports: feature("reports", "list"),
  reportVersions: feature("reports", "versions.read"),
  playbooks: feature("playbooks", "list"),
  playbookRuns: feature("playbooks", "runs.read"),
  aiWorkers: feature("ai-workers", "list"),
  knowledgeNodes: feature("knowledge", "nodes.read"),
  knowledgeEdges: feature("knowledge", "edges.read"),
  knowledgeGraph: feature("knowledge", "graph.read"),
  governancePolicies: feature("governance", "policies.read"),
  governanceApprovals: feature("governance", "approvals.read"),
  auditLogs: feature("audit", "logs.read"),
  auditIntegrity: feature("audit", "integrity.read"),
  incidents: feature("incidents", "list"),
  notifications: feature("notifications", "list"),
  privacyRequests: feature("privacy", "requests.read"),
  integrations: feature("integrations", "list"),
  globalSearch: feature("search", "global.read"),
  operationsHealth: feature("operations", "health.read"),
});
