export type ApiMethod = "GET" | "POST" | "PATCH" | "DELETE";
export type ApiRisk = "read" | "write" | "execute" | "admin";

export type ApiEndpointContract = {
  method: ApiMethod;
  path: string;
  group: string;
  risk: ApiRisk;
  safety?: "governed" | "simulation_only";
};

const endpoint = (group: string, risk: ApiRisk, method: ApiMethod, path: string, safety?: ApiEndpointContract["safety"]): ApiEndpointContract => ({ group, risk, method, path, ...(safety ? { safety } : {}) });

export const API_V1_CONTRACT: readonly ApiEndpointContract[] = [
  endpoint("auth", "write", "POST", "/api/v1/auth/register"), endpoint("auth", "write", "POST", "/api/v1/auth/login"), endpoint("auth", "write", "POST", "/api/v1/auth/logout"), endpoint("auth", "write", "POST", "/api/v1/auth/refresh"), endpoint("auth", "write", "POST", "/api/v1/auth/google"), endpoint("auth", "write", "POST", "/api/v1/auth/forgot-password"), endpoint("auth", "write", "POST", "/api/v1/auth/reset-password"), endpoint("auth", "write", "POST", "/api/v1/auth/verify-email"), endpoint("auth", "write", "POST", "/api/v1/auth/mfa/setup"), endpoint("auth", "write", "POST", "/api/v1/auth/mfa/verify"), endpoint("auth", "write", "POST", "/api/v1/auth/mfa/disable"), endpoint("auth", "read", "GET", "/api/v1/auth/sessions"), endpoint("auth", "write", "DELETE", "/api/v1/auth/sessions/:id"), endpoint("auth", "write", "DELETE", "/api/v1/auth/sessions/all"),
  endpoint("identity", "read", "GET", "/api/v1/me"), endpoint("identity", "write", "PATCH", "/api/v1/me"), endpoint("identity", "write", "PATCH", "/api/v1/me/password"), endpoint("identity", "read", "GET", "/api/v1/me/devices"), endpoint("identity", "write", "POST", "/api/v1/me/devices/:id/trust"), endpoint("identity", "write", "DELETE", "/api/v1/me/devices/:id"), endpoint("identity", "read", "GET", "/api/v1/me/api-keys"), endpoint("identity", "write", "POST", "/api/v1/me/api-keys"), endpoint("identity", "write", "DELETE", "/api/v1/me/api-keys/:id"), endpoint("identity", "read", "GET", "/api/v1/me/security-events"), endpoint("identity", "read", "GET", "/api/v1/me/credentials"), endpoint("identity", "write", "POST", "/api/v1/me/credentials"), endpoint("identity", "write", "DELETE", "/api/v1/me/credentials/:id"),
  endpoint("organization", "read", "GET", "/api/v1/organizations"), endpoint("organization", "write", "POST", "/api/v1/organizations"), endpoint("organization", "read", "GET", "/api/v1/organizations/:id"), endpoint("organization", "write", "PATCH", "/api/v1/organizations/:id"), endpoint("organization", "write", "DELETE", "/api/v1/organizations/:id"), endpoint("organization", "read", "GET", "/api/v1/organizations/:id/members"), endpoint("organization", "write", "POST", "/api/v1/organizations/:id/members"), endpoint("organization", "write", "PATCH", "/api/v1/organizations/:id/members/:userId"), endpoint("organization", "write", "DELETE", "/api/v1/organizations/:id/members/:userId"), endpoint("organization", "write", "POST", "/api/v1/organizations/:id/leave"),
  endpoint("workspace", "read", "GET", "/api/v1/workspaces"), endpoint("workspace", "write", "POST", "/api/v1/workspaces"), endpoint("workspace", "read", "GET", "/api/v1/workspaces/:id"), endpoint("workspace", "write", "PATCH", "/api/v1/workspaces/:id"), endpoint("workspace", "write", "DELETE", "/api/v1/workspaces/:id"), endpoint("workspace", "read", "GET", "/api/v1/workspaces/:id/members"), endpoint("workspace", "write", "POST", "/api/v1/workspaces/:id/members"), endpoint("workspace", "write", "PATCH", "/api/v1/workspaces/:id/members/:userId"), endpoint("workspace", "write", "DELETE", "/api/v1/workspaces/:id/members/:userId"), endpoint("workspace", "write", "POST", "/api/v1/workspaces/:id/switch"), endpoint("workspace", "read", "GET", "/api/v1/workspaces/:id/tags"), endpoint("workspace", "write", "POST", "/api/v1/workspaces/:id/tags"), endpoint("workspace", "read", "GET", "/api/v1/workspaces/:id/notes"), endpoint("workspace", "write", "POST", "/api/v1/workspaces/:id/notes"), endpoint("workspace", "write", "DELETE", "/api/v1/workspaces/:id/notes/:noteId"),
  endpoint("research", "read", "GET", "/api/v1/researches"), endpoint("research", "write", "POST", "/api/v1/researches"), endpoint("research", "read", "GET", "/api/v1/researches/:id"), endpoint("research", "write", "PATCH", "/api/v1/researches/:id"), endpoint("research", "write", "DELETE", "/api/v1/researches/:id"), endpoint("research", "execute", "POST", "/api/v1/researches/:id/start", "governed"), endpoint("research", "execute", "POST", "/api/v1/researches/:id/pause", "governed"), endpoint("research", "execute", "POST", "/api/v1/researches/:id/resume", "governed"), endpoint("research", "execute", "POST", "/api/v1/researches/:id/cancel", "governed"), endpoint("research", "read", "GET", "/api/v1/researches/:id/tasks"), endpoint("research", "write", "POST", "/api/v1/researches/:id/tasks"), endpoint("research", "write", "PATCH", "/api/v1/researches/:id/tasks/:taskId"), endpoint("research", "read", "GET", "/api/v1/researches/:id/hypotheses"), endpoint("research", "write", "POST", "/api/v1/researches/:id/hypotheses"), endpoint("research", "write", "PATCH", "/api/v1/researches/:id/hypotheses/:hypId"), endpoint("research", "read", "GET", "/api/v1/researches/:id/observations"), endpoint("research", "read", "GET", "/api/v1/researches/:id/evidence"), endpoint("research", "read", "GET", "/api/v1/researches/:id/findings"), endpoint("research", "read", "GET", "/api/v1/researches/:id/executions"), endpoint("research", "read", "GET", "/api/v1/researches/:id/timeline"), endpoint("research", "read", "GET", "/api/v1/researches/:id/assets"), endpoint("research", "write", "POST", "/api/v1/researches/:id/assets"), endpoint("research", "write", "DELETE", "/api/v1/researches/:id/assets/:assetId"), endpoint("research", "write", "POST", "/api/v1/researches/:id/duplicate"),
  endpoint("assets", "read", "GET", "/api/v1/assets"), endpoint("assets", "write", "POST", "/api/v1/assets"), endpoint("assets", "read", "GET", "/api/v1/assets/:id"), endpoint("assets", "write", "PATCH", "/api/v1/assets/:id"), endpoint("assets", "write", "DELETE", "/api/v1/assets/:id"), endpoint("assets", "read", "GET", "/api/v1/assets/:id/relations"), endpoint("assets", "write", "POST", "/api/v1/assets/:id/relations"), endpoint("assets", "read", "GET", "/api/v1/assets/:id/findings"), endpoint("assets", "read", "GET", "/api/v1/assets/:id/evidence"),
  endpoint("tools", "read", "GET", "/api/v1/tools"), endpoint("tools", "read", "GET", "/api/v1/tools/:id"), endpoint("tools", "execute", "POST", "/api/v1/tools/:id/health-check", "governed"), endpoint("tools", "execute", "POST", "/api/v1/tools/:id/execute", "governed"), endpoint("tools", "read", "GET", "/api/v1/tools/capabilities"), endpoint("tools", "read", "GET", "/api/v1/tools/installed"), endpoint("tools", "read", "GET", "/api/v1/tools/health"), endpoint("tools", "read", "GET", "/api/v1/tools/executions"), endpoint("tools", "read", "GET", "/api/v1/tools/executions/:id"), endpoint("tools", "execute", "POST", "/api/v1/tools/executions/:id/cancel", "governed"), endpoint("tools", "read", "GET", "/api/v1/tools/executions/:id/output"), endpoint("tools", "read", "GET", "/api/v1/tools/catalog/:id/versions"),
  endpoint("ai", "read", "GET", "/api/v1/ai/providers"), endpoint("ai", "read", "GET", "/api/v1/ai/providers/:id/health"), endpoint("ai", "read", "GET", "/api/v1/ai/models"), endpoint("ai", "read", "GET", "/api/v1/ai/connections"), endpoint("ai", "write", "POST", "/api/v1/ai/connections"), endpoint("ai", "write", "DELETE", "/api/v1/ai/connections/:id"), endpoint("ai", "read", "GET", "/api/v1/ai/routing"), endpoint("ai", "write", "PATCH", "/api/v1/ai/routing"), endpoint("ai", "read", "GET", "/api/v1/ai/usage"), endpoint("ai", "read", "GET", "/api/v1/ai/usage/:workspaceId"), endpoint("ai", "read", "GET", "/api/v1/ai/prompts"), endpoint("ai", "write", "POST", "/api/v1/ai/prompts"), endpoint("ai", "read", "GET", "/api/v1/ai/prompts/:id/versions"), endpoint("ai", "write", "POST", "/api/v1/ai/prompts/:id/versions"), endpoint("ai", "execute", "POST", "/api/v1/ai/analyze", "governed"),
  endpoint("evidence", "read", "GET", "/api/v1/evidence"), endpoint("evidence", "write", "POST", "/api/v1/evidence"), endpoint("evidence", "read", "GET", "/api/v1/evidence/:id"), endpoint("evidence", "write", "PATCH", "/api/v1/evidence/:id"), endpoint("evidence", "write", "DELETE", "/api/v1/evidence/:id"), endpoint("evidence", "read", "GET", "/api/v1/evidence/:id/origin"), endpoint("evidence", "write", "POST", "/api/v1/evidence/:id/upload"), endpoint("evidence", "read", "GET", "/api/v1/evidence/:id/download"),
  endpoint("findings", "read", "GET", "/api/v1/findings"), endpoint("findings", "write", "POST", "/api/v1/findings"), endpoint("findings", "read", "GET", "/api/v1/findings/:id"), endpoint("findings", "write", "PATCH", "/api/v1/findings/:id"), endpoint("findings", "write", "DELETE", "/api/v1/findings/:id"), endpoint("findings", "write", "POST", "/api/v1/findings/:id/status"), endpoint("findings", "write", "POST", "/api/v1/findings/:id/assign"), endpoint("findings", "execute", "POST", "/api/v1/findings/:id/retest", "governed"), endpoint("findings", "read", "GET", "/api/v1/findings/:id/comments"), endpoint("findings", "write", "POST", "/api/v1/findings/:id/comments"), endpoint("findings", "read", "GET", "/api/v1/findings/:id/evidence"), endpoint("findings", "write", "POST", "/api/v1/findings/:id/evidence"), endpoint("findings", "write", "DELETE", "/api/v1/findings/:id/evidence/:evidenceId"),
  endpoint("reports", "read", "GET", "/api/v1/reports"), endpoint("reports", "write", "POST", "/api/v1/reports"), endpoint("reports", "read", "GET", "/api/v1/reports/:id"), endpoint("reports", "write", "PATCH", "/api/v1/reports/:id"), endpoint("reports", "write", "DELETE", "/api/v1/reports/:id"), endpoint("reports", "execute", "POST", "/api/v1/reports/:id/generate", "governed"), endpoint("reports", "write", "POST", "/api/v1/reports/:id/send"), endpoint("reports", "read", "GET", "/api/v1/reports/:id/versions"),
  endpoint("playbooks", "read", "GET", "/api/v1/playbooks"), endpoint("playbooks", "write", "POST", "/api/v1/playbooks"), endpoint("playbooks", "read", "GET", "/api/v1/playbooks/:id"), endpoint("playbooks", "write", "PATCH", "/api/v1/playbooks/:id"), endpoint("playbooks", "write", "DELETE", "/api/v1/playbooks/:id"), endpoint("playbooks", "execute", "POST", "/api/v1/playbooks/:id/run", "governed"), endpoint("playbooks", "read", "GET", "/api/v1/playbooks/:id/runs"),
  endpoint("ai-workers", "read", "GET", "/api/v1/ai/workers"), endpoint("ai-workers", "write", "POST", "/api/v1/ai/workers"), endpoint("ai-workers", "read", "GET", "/api/v1/ai/workers/:id"), endpoint("ai-workers", "write", "PATCH", "/api/v1/ai/workers/:id"), endpoint("ai-workers", "write", "DELETE", "/api/v1/ai/workers/:id"), endpoint("ai-workers", "execute", "POST", "/api/v1/ai/workers/:id/run", "governed"),
  endpoint("knowledge", "read", "GET", "/api/v1/knowledge/nodes"), endpoint("knowledge", "write", "POST", "/api/v1/knowledge/nodes"), endpoint("knowledge", "read", "GET", "/api/v1/knowledge/edges"), endpoint("knowledge", "write", "POST", "/api/v1/knowledge/edges"), endpoint("knowledge", "read", "GET", "/api/v1/knowledge/graph"), endpoint("knowledge", "read", "GET", "/api/v1/knowledge/search"),
  endpoint("governance", "read", "GET", "/api/v1/governance/policies"), endpoint("governance", "write", "POST", "/api/v1/governance/policies"), endpoint("governance", "read", "GET", "/api/v1/governance/policies/:id"), endpoint("governance", "write", "PATCH", "/api/v1/governance/policies/:id"), endpoint("governance", "write", "DELETE", "/api/v1/governance/policies/:id"), endpoint("governance", "read", "GET", "/api/v1/governance/approvals"), endpoint("governance", "admin", "POST", "/api/v1/governance/approvals/:id/approve"), endpoint("governance", "admin", "POST", "/api/v1/governance/approvals/:id/reject"), endpoint("governance", "admin", "POST", "/api/v1/governance/approvals/:id/escalate"),
  endpoint("audit", "read", "GET", "/api/v1/audit/logs"), endpoint("audit", "read", "GET", "/api/v1/audit/logs/:id"), endpoint("audit", "read", "GET", "/api/v1/audit/integrity"), endpoint("audit", "read", "GET", "/api/v1/audit/archives"),
  endpoint("incidents", "read", "GET", "/api/v1/incidents"), endpoint("incidents", "write", "POST", "/api/v1/incidents"), endpoint("incidents", "read", "GET", "/api/v1/incidents/:id"), endpoint("incidents", "write", "PATCH", "/api/v1/incidents/:id"), endpoint("incidents", "write", "POST", "/api/v1/incidents/:id/acknowledge"), endpoint("incidents", "admin", "POST", "/api/v1/incidents/:id/escalate"), endpoint("incidents", "write", "POST", "/api/v1/incidents/:id/resolve"), endpoint("incidents", "read", "GET", "/api/v1/incidents/:id/reviews"), endpoint("incidents", "write", "POST", "/api/v1/incidents/:id/reviews"),
  endpoint("notifications", "read", "GET", "/api/v1/notifications"), endpoint("notifications", "write", "PATCH", "/api/v1/notifications/:id/read"), endpoint("notifications", "write", "POST", "/api/v1/notifications/read-all"), endpoint("notifications", "read", "GET", "/api/v1/notifications/preferences"), endpoint("notifications", "write", "PATCH", "/api/v1/notifications/preferences"),
  endpoint("privacy", "read", "GET", "/api/v1/privacy/requests"), endpoint("privacy", "write", "POST", "/api/v1/privacy/export"), endpoint("privacy", "write", "POST", "/api/v1/privacy/deletion"), endpoint("privacy", "read", "GET", "/api/v1/privacy/requests/:id"),
  endpoint("billing", "read", "GET", "/api/v1/billing/subscription"), endpoint("billing", "write", "POST", "/api/v1/billing/subscription"), endpoint("billing", "write", "PATCH", "/api/v1/billing/subscription"), endpoint("billing", "write", "DELETE", "/api/v1/billing/subscription"), endpoint("billing", "read", "GET", "/api/v1/billing/invoices"), endpoint("billing", "read", "GET", "/api/v1/billing/usage"), endpoint("billing", "write", "POST", "/api/v1/billing/webhook"),
  endpoint("integrations", "read", "GET", "/api/v1/integrations"), endpoint("integrations", "read", "GET", "/api/v1/integrations/connected"), endpoint("integrations", "write", "POST", "/api/v1/integrations/github"), endpoint("integrations", "write", "POST", "/api/v1/integrations/gitlab"), endpoint("integrations", "write", "POST", "/api/v1/integrations/slack"), endpoint("integrations", "write", "POST", "/api/v1/integrations/discord"), endpoint("integrations", "write", "POST", "/api/v1/integrations/webhook"), endpoint("integrations", "write", "DELETE", "/api/v1/integrations/:id"), endpoint("integrations", "write", "POST", "/api/v1/integrations/:id/test"),
  endpoint("search", "read", "GET", "/api/v1/search"), endpoint("search", "read", "GET", "/api/v1/search/:entityType"),
  endpoint("operations", "read", "GET", "/api/v1/operations/health"), endpoint("operations", "read", "GET", "/api/v1/operations/metrics"), endpoint("operations", "read", "GET", "/api/v1/operations/queue"), endpoint("operations", "read", "GET", "/api/v1/operations/workers"),
  endpoint("admin", "admin", "GET", "/api/v1/admin/users"), endpoint("admin", "admin", "PATCH", "/api/v1/admin/users/:id"), endpoint("admin", "admin", "DELETE", "/api/v1/admin/users/:id"), endpoint("admin", "admin", "GET", "/api/v1/admin/organizations"), endpoint("admin", "admin", "GET", "/api/v1/admin/audit"), endpoint("admin", "admin", "POST", "/api/v1/admin/feature-flags"), endpoint("admin", "admin", "GET", "/api/v1/admin/abuse"),
  endpoint("breakglass", "admin", "POST", "/api/v1/breakglass/request", "governed"), endpoint("breakglass", "admin", "GET", "/api/v1/breakglass/requests"), endpoint("breakglass", "admin", "POST", "/api/v1/breakglass/requests/:id/approve", "governed"), endpoint("breakglass", "admin", "POST", "/api/v1/breakglass/requests/:id/revoke", "governed"),
  endpoint("redteam", "read", "GET", "/api/v1/redteam/implants", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/implants", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/implants/:id", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/implants/:id/beacon", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/implants/:id/command", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/implants/:id/commands", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/operations", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/operations", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/operations/:id", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/phishing/campaigns", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/phishing/campaigns/:id/stats", "simulation_only"), endpoint("redteam", "execute", "POST", "/api/v1/redteam/phishing/campaigns/:id/send", "simulation_only"), endpoint("redteam", "read", "GET", "/api/v1/redteam/phishing/campaigns/:id/click", "simulation_only"),
  endpoint("purpleteam", "read", "GET", "/api/v1/purpleteam/exercises"), endpoint("purpleteam", "write", "POST", "/api/v1/purpleteam/exercises"), endpoint("purpleteam", "read", "GET", "/api/v1/purpleteam/exercises/:id"), endpoint("purpleteam", "execute", "POST", "/api/v1/purpleteam/exercises/:id/run", "governed"), endpoint("purpleteam", "read", "GET", "/api/v1/purpleteam/exercises/:id/gap"), endpoint("purpleteam", "write", "POST", "/api/v1/purpleteam/exercises/:id/gap/improve"),
  endpoint("bugbounty", "read", "GET", "/api/v1/bugbounty/programs"), endpoint("bugbounty", "write", "POST", "/api/v1/bugbounty/programs"), endpoint("bugbounty", "read", "GET", "/api/v1/bugbounty/programs/:id"), endpoint("bugbounty", "write", "POST", "/api/v1/bugbounty/programs/:id/submission"), endpoint("bugbounty", "read", "GET", "/api/v1/bugbounty/submissions"), endpoint("bugbounty", "read", "GET", "/api/v1/bugbounty/submissions/:id"), endpoint("bugbounty", "write", "POST", "/api/v1/bugbounty/submissions/:id/validate"), endpoint("bugbounty", "admin", "POST", "/api/v1/bugbounty/submissions/:id/payout"),
  endpoint("execution", "read", "GET", "/api/v1/executions/:jobId"), endpoint("execution", "execute", "POST", "/api/v1/simulations/run", "simulation_only"), endpoint("research-execution", "execute", "POST", "/api/v1/research-tasks/:taskId/execute", "governed"), endpoint("search", "read", "GET", "/api/v1/workspaces/:workspaceId/search"), endpoint("ai-runs", "read", "GET", "/api/v1/workspaces/:workspaceId/ai-runs"), endpoint("ai-runs", "read", "GET", "/api/v1/ai-runs/:runId"), endpoint("research-workflow", "write", "POST", "/api/v1/workspaces/:workspaceId/research-sessions"), endpoint("research-workflow", "read", "GET", "/api/v1/research-sessions/:sessionId/assets"), endpoint("research-workflow", "write", "POST", "/api/v1/research-sessions/:sessionId/assets"), endpoint("research-workflow", "write", "POST", "/api/v1/research-sessions/:sessionId/observations"), endpoint("research-workflow", "write", "POST", "/api/v1/research-sessions/:sessionId/findings"), endpoint("tools", "read", "GET", "/api/v1/tools/catalog"), endpoint("tools", "read", "GET", "/api/v1/tools/summary"), endpoint("tools", "read", "GET", "/api/v1/tools/search"), endpoint("tools", "read", "GET", "/api/v1/tools/runtime"), endpoint("tools", "execute", "POST", "/api/v1/workspaces/:workspaceId/tools/execute", "governed"),
];

export const API_V1_BLUEPRINT_GROUPS = 28;
export const API_V1_BLUEPRINT_TARGET = "260+" as const;
export const API_V1_NAMED_ENDPOINTS = API_V1_CONTRACT.length;

export function getApiContractSummary() {
  const groups = Object.fromEntries([...new Set(API_V1_CONTRACT.map(item => item.group))].map(group => [group, API_V1_CONTRACT.filter(item => item.group === group).length]));
  return { apiVersion: "v1", blueprintGroups: API_V1_BLUEPRINT_GROUPS, blueprintTarget: API_V1_BLUEPRINT_TARGET, namedContractEndpoints: API_V1_NAMED_ENDPOINTS, groups };
}
