import type { Express, Request, Response } from "express";
import { sdk } from "./_core/sdk";
import { canAccessWorkspace } from "./control-plane/operations";
import { addPurpleTeamImprovement, approvePurpleTeamExercise, createPurpleTeamExercise, getPurpleTeamExercise, getPurpleTeamGap, listDetectionRules, listPurpleTeamExercises, listPurpleTeamImprovements, listPurpleTeamScenarios, planPurpleTeamExercise, registerDetectionRule, runPurpleTeamExercise } from "./purple-team";

async function uid(req: Request) { const user = await sdk.authenticateRequest(req); if (!user) throw new Error("Authentication required"); return Number(user.id); }
function fail(res: Response, e: unknown) { res.status(400).json({ error: e instanceof Error ? e.message : "request rejected" }); }

export function registerPurpleTeamRestV1Routes(app: Express) {
  app.get("/api/v1/purpleteam/exercises", async (req, res) => { try { const id = await uid(req); const workspaceId = Number(req.query.workspaceId); if (!(await canAccessWorkspace(id, workspaceId, "read"))) return res.status(403).json({ error: "Forbidden" }); res.json({ exercises: listPurpleTeamExercises(id, workspaceId) }); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/exercises", async (req, res) => { try { const id = await uid(req); const workspaceId = Number(req.body?.workspaceId); if (!(await canAccessWorkspace(id, workspaceId, "manage"))) return res.status(403).json({ error: "Forbidden" }); res.status(201).json(createPurpleTeamExercise(id, { ...req.body, workspaceId })); } catch (e) { fail(res, e); } });
  app.get("/api/v1/purpleteam/exercises/:id", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "read"))) return res.status(403).json({ error: "Forbidden" }); res.json(exercise); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/exercises/:id/plan", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "manage"))) return res.status(403).json({ error: "Forbidden" }); res.json(planPurpleTeamExercise(id, req.params.id)); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/exercises/:id/approve", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "manage"))) return res.status(403).json({ error: "Forbidden" }); res.json(approvePurpleTeamExercise(id, req.params.id)); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/exercises/:id/run", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "manage"))) return res.status(403).json({ error: "Forbidden" }); res.json(runPurpleTeamExercise(id, req.params.id)); } catch (e) { fail(res, e); } });
  app.get("/api/v1/purpleteam/exercises/:id/gap", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "read"))) return res.status(403).json({ error: "Forbidden" }); res.json({ exerciseId: exercise.id, status: exercise.status, gap: getPurpleTeamGap(id, exercise.id) }); } catch (e) { fail(res, e); } });
  app.get("/api/v1/purpleteam/exercises/:id/improvements", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "read"))) return res.status(403).json({ error: "Forbidden" }); res.json({ improvements: listPurpleTeamImprovements(req.params.id) }); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/exercises/:id/gap/improve", async (req, res) => { try { const id = await uid(req); const exercise = getPurpleTeamExercise(id, req.params.id); if (!(await canAccessWorkspace(id, exercise.workspaceId, "manage"))) return res.status(403).json({ error: "Forbidden" }); res.status(201).json(addPurpleTeamImprovement(id, { ...req.body, exerciseId: req.params.id })); } catch (e) { fail(res, e); } });
  app.get("/api/v1/purpleteam/scenarios", async (req, res) => { try { await uid(req); res.json({ scenarios: listPurpleTeamScenarios() }); } catch (e) { fail(res, e); } });
  app.get("/api/v1/purpleteam/detection-rules", async (req, res) => { try { await uid(req); res.json({ rules: listDetectionRules() }); } catch (e) { fail(res, e); } });
  app.post("/api/v1/purpleteam/detection-rules", async (req, res) => { try { await uid(req); res.status(201).json(registerDetectionRule(req.body)); } catch (e) { fail(res, e); } });
}
