import { and, desc, eq } from "drizzle-orm";
import { tagAssignments, workspaceNotes, workspaceTags } from "../drizzle/schema";
import { getDb } from "./db";
import { canAccessWorkspace } from "./control-plane/operations";

async function access(userId: number, workspaceId: number, intent: "read" | "manage" = "read") {
  if (!(await canAccessWorkspace(userId, workspaceId, intent))) throw new Error("Workspace tidak ditemukan atau tidak dapat diakses.");
}
export async function listTags(userId: number, workspaceId: number) { await access(userId, workspaceId); const db = await getDb(); return db ? db.select().from(workspaceTags).where(eq(workspaceTags.workspaceId, workspaceId)).orderBy(desc(workspaceTags.createdAt)) : []; }
export async function upsertTag(userId: number, input: { workspaceId: number; name: string; color?: string }) { await access(userId, input.workspaceId, "manage"); const name = input.name.trim(); if (name.length < 2 || name.length > 80) throw new Error("Tag name must be between 2 and 80 characters."); const db = await getDb(); if (!db) throw new Error("Database tidak tersedia."); await db.insert(workspaceTags).values({ workspaceId: input.workspaceId, name, color: input.color?.trim() || "#22d3ee", createdByUserId: userId }).onDuplicateKeyUpdate({ set: { color: input.color?.trim() || "#22d3ee" } }); const [tag] = await db.select().from(workspaceTags).where(and(eq(workspaceTags.workspaceId, input.workspaceId), eq(workspaceTags.name, name))).limit(1); return tag; }
export async function listAssignments(userId: number, input: { workspaceId: number; entityType: string; entityId: number }) { await access(userId, input.workspaceId); const db = await getDb(); return db ? db.select({ assignment: tagAssignments, tag: workspaceTags }).from(tagAssignments).innerJoin(workspaceTags, eq(tagAssignments.tagId, workspaceTags.id)).where(and(eq(tagAssignments.workspaceId, input.workspaceId), eq(tagAssignments.entityType, input.entityType), eq(tagAssignments.entityId, input.entityId))) : []; }
export async function assignTag(userId: number, input: { workspaceId: number; tagId: number; entityType: string; entityId: number }) { await access(userId, input.workspaceId, "manage"); const db = await getDb(); if (!db) throw new Error("Database tidak tersedia."); const [tag] = await db.select().from(workspaceTags).where(and(eq(workspaceTags.id, input.tagId), eq(workspaceTags.workspaceId, input.workspaceId))).limit(1); if (!tag) throw new Error("Tag tidak ditemukan."); await db.insert(tagAssignments).values({ ...input, assignedByUserId: userId }).onDuplicateKeyUpdate({ set: { assignedByUserId: userId } }); return { success: true as const }; }
export async function listNotes(userId: number, input: { workspaceId: number; entityType?: string; entityId?: number }) { await access(userId, input.workspaceId); const db = await getDb(); if (!db) return []; const conditions = [eq(workspaceNotes.workspaceId, input.workspaceId), input.entityType ? eq(workspaceNotes.entityType, input.entityType) : undefined, input.entityId ? eq(workspaceNotes.entityId, input.entityId) : undefined].filter(Boolean) as any[]; return db.select().from(workspaceNotes).where(and(...conditions)).orderBy(desc(workspaceNotes.updatedAt)); }
export async function createNote(userId: number, input: { workspaceId: number; entityType: string; entityId?: number; title: string; body: string; visibility?: "private" | "workspace" }) { await access(userId, input.workspaceId, "read"); const title = input.title.trim(); const body = input.body.trim(); if (title.length < 2 || body.length < 1) throw new Error("Note title and body are required."); const db = await getDb(); if (!db) throw new Error("Database tidak tersedia."); const [note] = await db.insert(workspaceNotes).values({ workspaceId: input.workspaceId, authorUserId: userId, entityType: input.entityType.trim(), entityId: input.entityId, title, body, visibility: input.visibility || "workspace" }).$returningId(); return db.select().from(workspaceNotes).where(eq(workspaceNotes.id, note.id)).limit(1).then(rows => rows[0]); }
