import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const assuranceFile = path.join(root, "client/src/pages/Assurance.tsx");
const notificationsFile = path.join(root, "client/src/pages/Notifications.tsx");
const assurancePairs = [
  ["<Eyebrow>Policy control · incident response · activation gate</Eyebrow>", "<Eyebrow>{copy(\"assurance.eyebrow\")}</Eyebrow>"], ["Assurance <span className=\"neon-pink\">Control</span>", "{copy(\"assurance.title\")}"], ["Every policy change and outbound-delivery activation follows a distinct-reviewer decision path. Incidents are workspace-scoped, timestamped, and retained in audit evidence.", "{copy(\"assurance.description\")}"],
  ["<Eyebrow>Reviewer evidence</Eyebrow>", "<Eyebrow>{copy(\"assurance.reviewerEvidence\")}</Eyebrow>"], [">Policy diff ledger</h2>", ">{copy(\"assurance.policyDiffLedger\")}</h2>"], ["Changed fields: {fields.length ? fields.join(\", \") : \"no parsable diff\"}", "{copy(\"assurance.changedFields\")}: {fields.length ? fields.join(\", \") : copy(\"assurance.noParsableDiff\")}"], [">No policy versions awaiting review.</p>", ">{copy(\"assurance.noPolicyVersions\")}</p>"],
  ["<Eyebrow>Incident evidence</Eyebrow>", "<Eyebrow>{copy(\"assurance.incidentEvidence\")}</Eyebrow>"], [">Traceable links</h2>", ">{copy(\"assurance.traceableLinks\")}</h2>"], ["Attach an existing workspace evidence artifact by ID. The server rejects artifacts from another workspace and requires incident-response access.", "{copy(\"assurance.evidenceDescription\")}"], [">Select incident</option>", ">{copy(\"assurance.selectIncident\")}</option>"], ["placeholder=\"Evidence artifact ID\"", "placeholder={copy(\"assurance.evidenceArtifactId\")}"], [">Link</Button>", ">{copy(\"common.link\")}</Button>"], [">Select an incident to inspect evidence links.</p>", ">{copy(\"assurance.selectIncidentForEvidence\")}</p>"],
  ["<Eyebrow>Policy versioning</Eyebrow>", "<Eyebrow>{copy(\"assurance.policyVersioning\")}</Eyebrow>"], [">Change control</h2>", ">{copy(\"assurance.changeControl\")}</h2>"], ["A request remains pending until a distinct reviewer or administrator decides it. Only an approved version replaces the active workspace policy.", "{copy(\"assurance.policyRequestDescription\")}"], [">Select workspace</option>", ">{copy(\"assurance.selectWorkspace\")}</option>"], ["placeholder=\"Change summary\"", "placeholder={copy(\"assurance.changeSummary\")}"], ["placeholder=\"Safe-harbor text\"", "placeholder={copy(\"assurance.safeHarbor\")}"], ["placeholder=\"Code of conduct\"", "placeholder={copy(\"assurance.codeOfConduct\")}"], ["placeholder=\"Allowlist, one entry per line\"", "placeholder={copy(\"assurance.allowlist\")}"], ["placeholder=\"Exclusions, one entry per line\"", "placeholder={copy(\"assurance.exclusions\")}"], [">Request policy review</Button>", ">{copy(\"assurance.requestPolicyReview\")}</Button>"], ["placeholder=\"Review note\"", "placeholder={copy(\"assurance.reviewNote\")}"], [">Approve</Button>", ">{copy(\"common.approve\")}</Button>"], [">Reject</Button>", ">{copy(\"common.reject\")}</Button>"],
  ["<Eyebrow>Incident response</Eyebrow>", "<Eyebrow>{copy(\"assurance.incidentResponse\")}</Eyebrow>"], [">Escalation ledger</h2>", ">{copy(\"assurance.escalationLedger\")}</h2>"], ["placeholder=\"Incident title\"", "placeholder={copy(\"assurance.incidentTitle\")}"], ["placeholder=\"What happened, what is contained, and what requires review?\"", "placeholder={copy(\"assurance.incidentDescription\")}"], [">Open incident</Button>", ">{copy(\"assurance.openIncident\")}</Button>"], ["Escalation due: {<LocalizedDate", "{copy(\"assurance.escalationDue\")}: {<LocalizedDate"], [">Acknowledge</Button>", ">{copy(\"assurance.acknowledge\")}</Button>"], ["placeholder=\"Resolution note\"", "placeholder={copy(\"assurance.resolutionNote\")}"], [">Resolve</Button>", ">{copy(\"common.resolve\")}</Button>"],
  ["<Eyebrow>Outbound delivery gate</Eyebrow>", "<Eyebrow>{copy(\"assurance.outboundGate\")}</Eyebrow>"], [">Webhook activation reviews</h2>", ">{copy(\"assurance.webhookReviews\")}</h2>"], ["A workspace owner must first save a confirmed HTTPS draft with a secret reference in Operations Console. A separate reviewer can approve or reject the readiness request, but this release still performs no outbound network delivery.", "{copy(\"assurance.webhookDescription\")}"], ["Workspace #{request.workspaceId}", "{copy(\"assurance.workspace\")} #{request.workspaceId}"], ["placeholder=\"Reviewer decision note\"", "placeholder={copy(\"assurance.reviewerDecisionNote\")}"], [">No webhook activation request.</p>", ">{copy(\"assurance.noWebhookRequest\")}</p>"],
];
let assurance = await readFile(assuranceFile, "utf8");
assurance = assurance.replace('import { LocalizedDate } from "@/components/LocalizedDate";\n', 'import { LocalizedDate } from "@/components/LocalizedDate";\nimport { useLocale } from "@/contexts/LocaleContext";\n');
assurance = assurance.replace("export default function Assurance() { return", "export default function Assurance() { const { copy } = useLocale(); return");
for (const name of ["PolicyDiffPanel", "IncidentEvidencePanel", "PolicyPanel", "IncidentPanel", "WebhookActivationPanel"]) assurance = assurance.replace(`function ${name}() {`, `function ${name}() { const { copy } = useLocale();`);
for (const [from, to] of assurancePairs) assurance = assurance.replaceAll(from, to);
await writeFile(assuranceFile, assurance);

let notifications = await readFile(notificationsFile, "utf8");
notifications = notifications.replace('import { LocalizedDate } from "@/components/LocalizedDate";\n', 'import { LocalizedDate } from "@/components/LocalizedDate";\nimport { useLocale } from "@/contexts/LocaleContext";\n');
notifications = notifications.replace('  const utils = trpc.useUtils();', '  const { copy } = useLocale();\n  const utils = trpc.useUtils();');
const notificationPairs = [
  ["<Eyebrow>Custom alerts · in-app delivery</Eyebrow>", "<Eyebrow>{copy(\"notifications.eyebrow\")}</Eyebrow>"], ["Signal <span className=\"neon-pink\">Center</span>", "{copy(\"notifications.title\")}"], ["Persistent, user-scoped alerts for governance and safety events. No external recipient or webhook is activated from this screen.", "{copy(\"notifications.description\")}"], [">Mark all read</Button>", ">{copy(\"notifications.markAllRead\")}</Button>"], ["<Eyebrow>Delivery ledger</Eyebrow>", "<Eyebrow>{copy(\"notifications.deliveryLedger\")}</Eyebrow>"], ["{unread} unread signal{unread === 1 ? \"\" : \"s\"}", "{unread} {copy(unread === 1 ? \"notifications.unreadSignal\" : \"notifications.unreadSignals\")}"], [">Select to acknowledge</p>", ">{copy(\"notifications.selectToAcknowledge\")}</p>"], [">No notification records</p>", ">{copy(\"notifications.noRecords\")}</p>"], ["Alerts appear only after a governed event occurs; no synthetic activity has been added.", "{copy(\"notifications.noRecordsDescription\")}"], ["<Eyebrow>Event preferences</Eyebrow>", "<Eyebrow>{copy(\"notifications.eventPreferences\")}</Eyebrow>"], [">Alert matrix</h2>", ">{copy(\"notifications.alertMatrix\")}</h2>"], ["In-app delivery is enabled by default. Disabling an event suppresses its inbox alert and records the result in its workspace audit trail.", "{copy(\"notifications.preferencesDescription\")}"], ["<Eyebrow>External delivery boundary</Eyebrow>", "<Eyebrow>{copy(\"notifications.externalBoundary\")}</Eyebrow>"], ["Webhook, email, and chat integrations are intentionally unconfigured. Enabling one requires a recipient endpoint and credential managed as a secret, plus a delivery retry and signing policy.", "{copy(\"notifications.externalBoundaryDescription\")}"],
];
for (const [from, to] of notificationPairs) notifications = notifications.replaceAll(from, to);
await writeFile(notificationsFile, notifications);
console.log(`Applied ${assurancePairs.length} Assurance and ${notificationPairs.length} Signal Center explicit copy bindings.`);
